<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Core/RaTemplate.Application/RaTemplate.Application.csproj" />
    <ProjectReference Include="../../src/Core/RaTemplate.Domain/RaTemplate.Domain.csproj" />
    <ProjectReference Include="../../src/Infrastructure/RaTemplate.Infrastructure/RaTemplate.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Infrastructure/RaTemplate.Integration/RaTemplate.Integration.csproj" />
    <ProjectReference Include="../../src/Infrastructure/RaTemplate.Persistence/RaTemplate.Persistence.csproj" />
    <ProjectReference Include="../../src/Presentation/RaTemplate.Api/RaTemplate.Api.csproj" />
    <ProjectReference Include="../../src/Presentation/RaTemplate.Api.Contracts/RaTemplate.Api.Contracts.csproj" />
  </ItemGroup>
  
</Project>