<Project Sdk="Microsoft.NET.Sdk">

  
  <ItemGroup>
  <!--#if (UseEfSqlServer) -->
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  <!--#endif -->
   <!--#if (UseEfOracle) -->
    <PackageReference Include="Oracle.EntityFrameworkCore" />
  <!--#endif -->
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RA.Utilities.Data.EntityFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Core/RaTemplate.Application/RaTemplate.Application.csproj" />
  </ItemGroup>

</Project>
