<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Folder Include="Features/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RA.Utilities.Feature" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../RaTemplate.Domain/RaTemplate.Domain.csproj" />
  </ItemGroup>

</Project>
